/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Algoritmos;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFrame;
import javax.swing.JPanel;


/**
 *
 * @author javie
 */
public class VentanaGrafica extends javax.swing.JFrame {
    
    private ArrayList<Punto> puntos;
    private Punto punto1;
    private Punto punto2;
    /**
     * Creates new form Frame2
     * @param puntos
     * @param punto1
     * @param nombre
     * @param punto2
     */
     public VentanaGrafica(ArrayList<Punto> puntos, Punto punto1, Punto punto2, String nombre) {
        this.puntos = puntos;
        this.punto1 = punto1;
        this.punto2 = punto2;
        
        // Configuración de la ventana
        setTitle(nombre);
        setSize(800, 600);
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //setLocationRelativeTo(null);
        //setResizable(false);

        // Agregar el panel gráfico
        add(new PanelGrafico(puntos, punto1, punto2));
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        //initComponents();
        setVisible(true);
    }
     
     private void exitForm(java.awt.event.WindowEvent evt) {                          
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
class PanelGrafico extends JPanel {
        private ArrayList<Punto> puntos;
        private Punto punto1;
        private Punto punto2;

        public PanelGrafico(ArrayList<Punto> puntos, Punto punto1, Punto punto2) {
            this.puntos = puntos;
            this.punto1 = punto1;
            this.punto2 = punto2;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);        
            // Fondo blanco
            g.setColor(Color.WHITE);
            g.fillRect(0, 0, getWidth(), getHeight());

            // Dibujar los puntos
            g.setColor(Color.BLUE);
            for (Punto punto : puntos) {
                int x = (int)(punto.getX()*1);
                int y = (int)(punto.getY()*1);
                g.fillOval(x - 5, y - 5, 10, 10); // Dibujar un punto (círculo)
                
                g.drawString(Integer.toString(punto.getId()), x + 5, y - 5); // Coordenadas
            }

            // Dibujar la línea entre dos puntos
            g.setColor(Color.RED);
            int x1,x2,y1,y2,xmedio,ymedio;
            x1 = (int)(punto1.getX()*1);
            x2 = (int)(punto2.getX()*1);
            y1 = (int)(punto1.getY()*1);
            y2 = (int)(punto2.getY()*1);
            xmedio = (x1 + x2)/2;
            ymedio = (y1 + y2)/2;
            g.drawString("Distancia",xmedio,ymedio);
            g.drawLine(x1,y1,x2,y2);
        }
    }
}
